insert into public.cosmetics(cosmetic_id,name,kind,price) values
('species-pig','Cerdito alquimista','undefined',0),
('species-cat','Gato catalizador','undefined',500),
('species-dog','Perro de campo','undefined',650),
('hat-beanie','Beanie de enfoque','hat',100),
('hat-bucket','Bucket de terreno','hat',170),
('hat-scholar','Birrete de reconstrucción','hat',290),
('bag-field','Bolso de campo','bag',130),
('bag-lab','Bolso de laboratorio','bag',220),
('bag-sling','Sling de síntesis','bag',320),
('tail-classic','Cola de especie','tail',90),
('tail-comet','Estela cometa','tail',210),
('tail-ribbon','Cola de cinta','tail',350),
('focus-mode','Modo sin distracciones','feature',220),
('shirt-barca','Camiseta del Barça','shirt',260),
('shirt-real','Camiseta del Real Madrid','shirt',260),
('shirt-udechile','Camiseta de Universidad de Chile','shirt',240),
('shirt-colocolo','Camiseta de Colo-Colo','shirt',240),
('hat-asta-band','Cinta de antimagia','hat',360),
('hat-golden-circlet','Diadema Viento Áureo','hat',390),
('hat-bulls-hood','Capucha Toro Negro','hat',430),
('bag-grimoire','Morral del grimorio','bag',380),
('bag-bulls-mission','Mochila de misión Toro Negro','bag',410),
('bag-golden-wind','Mochila Viento Áureo','bag',440),
('tail-antimagic','Cola de antimagia','tail',400),
('tail-wind-spirit','Cola espíritu del viento','tail',430),
('tail-salamander','Cola de Salamandra','tail',460),
('scene-ruins','scene-ruins','scene',0),
('scene-forest','scene-forest','scene',90),
('scene-lab','scene-lab','scene',130),
('scene-sunset','scene-sunset','scene',170)
on conflict(cosmetic_id) do update set name=excluded.name, kind=excluded.kind, price=excluded.price;
