const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const { chromium } = require('playwright');
const dist = path.resolve(__dirname, '..', 'dist');
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.webp': 'image/webp', '.wasm': 'application/wasm' };
const server = http.createServer((request, response) => {
  const pathname = new URL(request.url, 'http://localhost').pathname;
  const file = path.resolve(dist, `.${decodeURIComponent(pathname === '/' ? '/index.html' : pathname)}`);
  if (!file.startsWith(`${dist}${path.sep}`)) return response.writeHead(403).end();
  fs.readFile(file, (error, bytes) => error ? response.writeHead(404).end() :
    response.writeHead(200, { 'Content-Type': types[path.extname(file)] || 'application/octet-stream' }).end(bytes));
});
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge', headless: true });
  const origin = `http://127.0.0.1:${server.address().port}/`;
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${origin}#/hub/calendar`);
    await page.locator('.calendar-interactive').waitFor();
    assert.equal(await page.evaluate(() => NEXO_SEMESTER.events.find(event => event.id === 'official-fq-c1')?.date), '2026-10-26');
    await page.locator('[data-daily-goal]').fill('135');
    await page.locator('[data-daily-goal]').press('Tab');
    assert.equal(await page.locator('[data-daily-goal]').inputValue(), '135');
    assert.match(await page.locator('.study-plan p').innerText(), /0 \/ 135 min/);
    await page.locator('.calendar-editor input[name=title]').fill('Pre-lab de Orgánica');
    await page.locator('.calendar-editor select[name=type]').selectOption('prelab');
    await page.locator('.calendar-editor input[name=date]').fill('2026-10-12');
    await page.locator('.calendar-editor input[name=prepMinutes]').fill('90');
    await page.locator('.calendar-editor button[type=submit]').click();
    await page.goto(`${origin}#/home`);
    await page.locator('.arcane-priorities').waitFor();
    assert(await page.locator('.arcane-priorities').innerText().then(text => text.includes('Pre-lab de Orgánica')));
    await page.goto(`${origin}#/hub/calendar`);
    assert.equal(await page.locator('[data-daily-goal]').inputValue(), '135');
    await page.locator('[data-calendar-day="2026-10-12"]').click();
    const row = page.locator('.calendar-selected .calendar-event').filter({ hasText: 'Pre-lab de Orgánica' });
    await row.locator('[data-calendar-toggle]').click();
    assert(await row.locator('small').first().innerText().then(text => text.includes('Hecho')));
    await page.goto(`${origin}#/home`);
    assert(!await page.locator('.arcane-priorities').innerText().then(text => text.includes('Pre-lab de Orgánica')));
    await page.goto(`${origin}#/hub/calendar`);
    await page.locator('.calendar-editor input[name=title]').fill('Laboratorio de prueba');
    await page.locator('.calendar-editor select[name=type]').selectOption('lab');
    assert(await page.locator('[data-lab-editor]').isVisible());
    await page.locator('.calendar-editor input[name=date]').fill('2026-10-15');
    await page.locator('input[name=labManual]').fill('Manual entregado en clase');
    await page.locator('input[name=labPrelabDate]').fill('2026-10-14');
    await page.locator('input[name=labReportDate]').fill('2026-10-22');
    await page.locator('textarea[name=labChecklist]').fill('Anotar mediciones\nRegistrar observaciones');
    await page.locator('.calendar-editor button[type=submit]').click();
    const lab = page.locator('.calendar-selected .calendar-event').filter({ hasText: 'Laboratorio de prueba' });
    assert.match(await lab.innerText(), /Antes[\s\S]*Pre-lab pendiente[\s\S]*Durante[\s\S]*Anotar mediciones[\s\S]*Después[\s\S]*Informe pendiente/);
    await lab.screenshot({ path: path.resolve(__dirname, '..', 'tmp', 'v11-visual', 'lab-mobile.png') });
    await lab.locator('[data-lab-stage=prelab]').click();
    assert.match(await lab.innerText(), /Pre-lab listo/);
    await page.reload();
    await page.locator('[data-calendar-next]').click();
    await page.locator('[data-calendar-day="2026-10-15"]').click();
    assert.match(await page.locator('.calendar-selected .calendar-event').filter({ hasText: 'Laboratorio de prueba' }).innerText(), /Pre-lab listo/);
    await page.goto(`${origin}#/hub/grades`);
    await page.locator('[data-grade-subject="analitica"]').click();
    assert.equal(await page.locator('[data-grade-course-weight="theory"]').inputValue(), '60');
    assert.match(await page.locator('.grade-result').innerText(), /Ponderación de teoría: 100\.00%/);
    await page.locator('[data-grade-group-tab="lab"]').click();
    assert.equal(await page.locator('[data-grade-course-weight="lab"]').inputValue(), '40');
    assert.match(await page.locator('.grade-result').innerText(), /Faltan ponderaciones/);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
    if(process.env.NEXO_SCREENSHOTS)await page.screenshot({path:path.resolve(__dirname,'..','tmp','v11-visual','grades-analitica-mobile.png'),fullPage:true});
    await page.locator('[data-action="add-grade-row"]').click();
    const labGrade=page.locator('.grade-row[data-grade-row],.grade-row').last();
    await labGrade.locator('[data-grade-field="weight"]').fill('100');
    await labGrade.locator('[data-grade-field="grade"]').fill('4');
    await page.locator('[data-grade-group-tab="theory"]').click();
    for(const row of await page.locator('.grade-row[data-grade-row],.grade-row').all()) {
      const grade=row.locator('[data-grade-field="grade"]');
      if(await grade.count())await grade.fill('5');
    }
    assert.match(await page.locator('.grade-result').innerText(), /Nota del ramo\s+4\.60/);
    if(process.env.NEXO_SCREENSHOTS)await page.screenshot({path:path.resolve(__dirname,'..','tmp','v11-visual','grades-analitica-complete-mobile.png'),fullPage:true});
    await page.evaluate(() => {
      const record=JSON.parse(localStorage.getItem('nexo-study-beta'));
      const event=record.events.find(item=>item.id==='official-fq-c1');
      event.date='2026-10-20';event.source='programa 2026';
      localStorage.setItem('nexo-study-beta',JSON.stringify(record));
    });
    await page.reload();
    await page.goto(`${origin}#/hub/calendar`);
    await page.locator('[data-daily-goal]').fill('136');
    await page.locator('[data-daily-goal]').press('Tab');
    await page.evaluate(()=>window.NexoStorage.flush());
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('nexo-study-beta')).events.find(item=>item.id==='official-fq-c1').date),'2026-10-26');
    await page.evaluate(() => {
      const record=JSON.parse(localStorage.getItem('nexo-study-beta'));
      const event=record.events.find(item=>item.id==='official-fq-c1');
      event.date='2026-10-20';event.source='manual';
      localStorage.setItem('nexo-study-beta',JSON.stringify(record));
    });
    await page.reload();
    await page.locator('[data-daily-goal]').fill('137');
    await page.locator('[data-daily-goal]').press('Tab');
    await page.evaluate(()=>window.NexoStorage.flush());
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('nexo-study-beta')).events.find(item=>item.id==='official-fq-c1').date),'2026-10-20','La corrección no debe pisar una fecha editada por el usuario.');
    assert.equal(errors.length, 0, errors.join('\n'));
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth);
    assert(overflow <= 1, `Horizontal overflow: ${overflow}px`);
    console.log('Bitácora E2E: meta, prioridad, laboratorios, Analítica 60/40, fechas y móvil OK');
  } finally { await browser.close(); server.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; server.close(); });
